"""
AI/ML Systems Security Patterns
LLM applications, ML pipelines, model serving, training security.
"""

AI_ML_PATTERNS = [

    # ─────────────────────────────────────────────
    # LLM APPLICATION SECURITY
    # ─────────────────────────────────────────────
    {
        'id': 'AIML-001',
        'category': 'AI/ML: LLM Security',
        'name': 'Prompt Injection - Direct User Input',
        'severity': 'CRITICAL',
        'pattern': r'(system_prompt|messages)\s*=.*\+.*\b(user_input|request|prompt|query)\b',
        'description': 'User input directly concatenated into LLM system prompt. Prompt injection/jailbreak.',
        'fix': 'Separate system and user roles. Sanitize user input. Use strict output parsing.',
        'langs': ['.py', '.js', '.ts'],
    },
    {
        'id': 'AIML-002',
        'category': 'AI/ML: LLM Security',
        'name': 'LLM Tool Calling Without Validation',
        'severity': 'CRITICAL',
        'pattern': r'(function_call|tool_calls|tool_choice)\s*.*\b(exec|subprocess|eval|os\.system)\b',
        'description': 'LLM function/tool calling with system execution capabilities and no input validation.',
        'fix': 'Validate all parameters before tool execution. Use allowlists. Never allow arbitrary code execution.',
        'langs': ['.py', '.js', '.ts'],
    },
    {
        'id': 'AIML-003',
        'category': 'AI/ML: LLM Security',
        'name': 'Excessive LLM Agency - File System Access',
        'severity': 'HIGH',
        'pattern': r'(tools|functions)\s*=.*["\'](read_file|write_file|delete_file|execute|shell|bash)["\']',
        'description': 'LLM agent given file system or shell execution tools without human approval gate.',
        'fix': 'Require human approval for destructive actions. Use read-only tools where possible.',
        'langs': ['.py', '.js', '.ts'],
    },
    {
        'id': 'AIML-004',
        'category': 'AI/ML: LLM Security',
        'name': 'No Output Validation on LLM Response',
        'severity': 'HIGH',
        'pattern': r'(completion|response|output)\s*=.*\.(create|generate|complete|chat)\s*\(',
        'negative_pattern': r'(validate|sanitize|parse|schema|pydantic|zod)',
        'description': 'LLM response used without validation. Malicious content in output could cause issues.',
        'fix': 'Parse and validate LLM output against expected schema. Use structured outputs/JSON mode.',
        'langs': ['.py', '.js', '.ts'],
    },
    {
        'id': 'AIML-005',
        'category': 'AI/ML: LLM Security',
        'name': 'LLM Context Window Poisoning',
        'severity': 'HIGH',
        'pattern': r'(retrieved_docs|search_results|context)\s*=.*\n.*messages\s*.*append\s*\(.*context',
        'description': 'RAG-retrieved content injected into context without sanitization. Indirect prompt injection.',
        'fix': 'Sanitize retrieved content. Use separate trust levels for retrieved vs user content.',
        'langs': ['.py', '.js', '.ts'],
    },
    {
        'id': 'AIML-006',
        'category': 'AI/ML: LLM Security',
        'name': 'API Key in LLM Client Init',
        'severity': 'CRITICAL',
        'pattern': r'(OpenAI|Anthropic|Cohere|Together|HuggingFace)\s*\(\s*api_key\s*=\s*["\'][A-Za-z0-9\-_]{10,}["\']',
        'description': 'LLM provider API key hardcoded in client initialization.',
        'fix': 'Use environment variable: api_key=os.environ["OPENAI_API_KEY"]',
        'langs': ['.py', '.js', '.ts'],
    },
    {
        'id': 'AIML-007',
        'category': 'AI/ML: LLM Security',
        'name': 'Insecure LangChain Tool Usage',
        'severity': 'HIGH',
        'pattern': r'\b(ShellTool|PythonREPLTool|BashProcess)\b|from\s+langchain.*Terminal',
        'description': 'LangChain shell/REPL tool gives LLM arbitrary code execution capability.',
        'fix': 'Never use shell/REPL tools in production. Use sandboxed execution environments.',
        'langs': ['.py'],
    },
    {
        'id': 'AIML-008',
        'category': 'AI/ML: LLM Security',
        'name': 'No Token/Cost Limits on LLM Calls',
        'severity': 'MEDIUM',
        'pattern': r'(client\.chat\.completions\.create|anthropic\.messages\.create|model\.generate)',
        'negative_pattern': r'(max_tokens|max_completion_tokens|max_length)',
        'description': 'LLM API call without max_tokens limit. Runaway costs or DoS possible.',
        'fix': 'Always set max_tokens. Implement per-user/per-request cost limits.',
        'langs': ['.py', '.js', '.ts'],
    },

    # ─────────────────────────────────────────────
    # ML PIPELINE SECURITY
    # ─────────────────────────────────────────────
    {
        'id': 'AIML-010',
        'category': 'AI/ML: Pipeline',
        'name': 'Model Loaded from Untrusted Source',
        'severity': 'CRITICAL',
        'pattern': r'(torch\.load|pickle\.load|tf\.saved_model\.load|joblib\.load)\s*\((?!.*trusted|.*local)',
        'description': 'ML model loaded without integrity verification. Malicious pickle payload possible.',
        'fix': 'Verify model checksums (SHA-256). Use safetensors format instead of pickle-based formats.',
        'langs': ['.py'],
    },
    {
        'id': 'AIML-011',
        'category': 'AI/ML: Pipeline',
        'name': 'Unsafe Model Deserialization',
        'severity': 'CRITICAL',
        'pattern': r'torch\.load\s*\((?!.*weights_only\s*=\s*True)',
        'description': 'PyTorch model loaded without weights_only=True. Arbitrary code execution via pickle.',
        'fix': 'Use torch.load(path, weights_only=True). Prefer safetensors format.',
        'langs': ['.py'],
    },
    {
        'id': 'AIML-012',
        'category': 'AI/ML: Pipeline',
        'name': 'Training Data Without Validation',
        'severity': 'MEDIUM',
        'pattern': r'(pd\.read_csv|pd\.read_json|np\.load|datasets\.load_dataset)\s*\(',
        'negative_pattern': r'(validate|schema|dtype|verify|check)',
        'description': 'Training data loaded without schema validation. Data poisoning via malformed inputs.',
        'fix': 'Validate data schema, types, ranges, and check for anomalies before training.',
        'langs': ['.py'],
    },
    {
        'id': 'AIML-013',
        'category': 'AI/ML: Pipeline',
        'name': 'PII in Training Data',
        'severity': 'HIGH',
        'pattern': r'(train_data|training_set|dataset)\s*.*\b(email|phone|ssn|credit_card|name|address)\b',
        'description': 'PII columns potentially included in training data. Model may memorize sensitive data.',
        'fix': 'Anonymize/pseudonymize PII before training. Use differential privacy techniques.',
        'langs': ['.py'],
    },
    {
        'id': 'AIML-014',
        'category': 'AI/ML: Pipeline',
        'name': 'MLflow Without Authentication',
        'severity': 'HIGH',
        'pattern': r'(mlflow\.set_tracking_uri|MLFLOW_TRACKING_URI)',
        'negative_pattern': r'(MLFLOW_TRACKING_USERNAME|MLFLOW_TRACKING_TOKEN|auth)',
        'description': 'MLflow tracking server without authentication. Model artifacts accessible to anyone.',
        'fix': 'Enable MLflow authentication. Use MLFLOW_TRACKING_TOKEN or reverse proxy with auth.',
        'langs': ['.py', '.yml', '.yaml'],
    },
    {
        'id': 'AIML-015',
        'category': 'AI/ML: Pipeline',
        'name': 'Model Served Without Input Validation',
        'severity': 'HIGH',
        'pattern': r'(@app\.route.*predict|predict_endpoint|inference_endpoint)',
        'negative_pattern': r'(validate|schema|pydantic|marshmallow|cerberus)',
        'description': 'ML model inference endpoint without input validation. Adversarial input attacks possible.',
        'fix': 'Validate all inputs against expected schema, ranges, and types before inference.',
        'langs': ['.py'],
    },
    {
        'id': 'AIML-016',
        'category': 'AI/ML: Pipeline',
        'name': 'Jupyter Notebook with Sensitive Data',
        'severity': 'HIGH',
        'pattern': r'(api_key|password|token|secret)\s*=\s*["\'][A-Za-z0-9_\-]{8,}["\']',
        'description': 'Credentials hardcoded in Jupyter notebook. Notebooks often committed with cell outputs.',
        'fix': 'Use python-dotenv or environment variables in notebooks. Strip outputs before commit.',
        'langs': ['.ipynb'],
    },
    {
        'id': 'AIML-017',
        'category': 'AI/ML: Pipeline',
        'name': 'Model Registry Without Access Control',
        'severity': 'MEDIUM',
        'pattern': r'(register_model|MlflowClient|model_registry|push_to_hub)',
        'negative_pattern': r'(private|token|access_token|authentication)',
        'description': 'Model pushed to registry without access controls.',
        'fix': 'Use private model repositories. Require authentication for model access.',
        'langs': ['.py'],
    },

    # ─────────────────────────────────────────────
    # VECTOR DB / RAG
    # ─────────────────────────────────────────────
    {
        'id': 'AIML-020',
        'category': 'AI/ML: Vector DB/RAG',
        'name': 'Vector DB Without Authentication',
        'severity': 'HIGH',
        'pattern': r'(Chroma|Pinecone|Weaviate|Qdrant|Milvus|FAISS)\s*\(',
        'negative_pattern': r'(api_key|token|auth|password)',
        'description': 'Vector database connected without authentication. Embeddings and data accessible.',
        'fix': 'Enable authentication on vector DB. Use API keys from environment variables.',
        'langs': ['.py', '.js', '.ts'],
    },
    {
        'id': 'AIML-021',
        'category': 'AI/ML: Vector DB/RAG',
        'name': 'RAG Without Access Control on Retrieved Docs',
        'severity': 'HIGH',
        'pattern': r'(similarity_search|query|retrieve)\s*\(',
        'negative_pattern': r'(filter|user_id|tenant|permission|access)',
        'description': 'RAG retrieval without per-user document filtering. Users may retrieve others\' documents.',
        'fix': 'Add metadata filters to vector search: filter={"user_id": current_user.id}',
        'langs': ['.py', '.js', '.ts'],
    },

    # ─────────────────────────────────────────────
    # MODEL DEPLOYMENT
    # ─────────────────────────────────────────────
    {
        'id': 'AIML-030',
        'category': 'AI/ML: Deployment',
        'name': 'Gradio/Streamlit App Without Auth',
        'severity': 'HIGH',
        'pattern': r'(gr\.Interface|gr\.Blocks|st\.write|streamlit\.run)',
        'negative_pattern': r'(auth|password|login|authenticate)',
        'description': 'ML demo app deployed without authentication. Model accessible to everyone.',
        'fix': 'Add Gradio auth: gr.Interface(..., auth=("user", "pass")). Use Streamlit-Authenticator.',
        'langs': ['.py'],
    },
    {
        'id': 'AIML-031',
        'category': 'AI/ML: Deployment',
        'name': 'Model Response Leaks Training Data',
        'severity': 'HIGH',
        'pattern': r'(system_prompt|SYSTEM_PROMPT)\s*=\s*["\'].*["\']',
        'description': 'System prompt hardcoded and potentially extractable via prompt injection.',
        'fix': 'Load system prompts from secure config. Implement guardrails to detect prompt extraction attempts.',
        'langs': ['.py', '.js', '.ts'],
    },
]
