"""
Mobile Application Security Patterns
Android, iOS, Flutter, React Native, Kotlin, Swift.
"""

MOBILE_PATTERNS = [

    # ─────────────────────────────────────────────
    # ANDROID
    # ─────────────────────────────────────────────
    {
        'id': 'MOB-001',
        'category': 'Mobile: Android',
        'name': 'Exported Activity Without Permission',
        'severity': 'HIGH',
        'pattern': r'android:exported=["\']true["\']',
        'negative_pattern': r'android:permission=',
        'description': 'Android component exported without permission check. Any app can interact with it.',
        'fix': 'Add android:permission or set android:exported="false". Only export if intentionally public.',
        'langs': ['.xml'],
    },
    {
        'id': 'MOB-002',
        'category': 'Mobile: Android',
        'name': 'Cleartext Traffic Allowed',
        'severity': 'HIGH',
        'pattern': r'android:usesCleartextTraffic=["\']true["\']',
        'description': 'App allows unencrypted HTTP traffic. Network eavesdropping possible.',
        'fix': 'Remove or set to false. Use network_security_config.xml to restrict to HTTPS.',
        'langs': ['.xml'],
    },
    {
        'id': 'MOB-003',
        'category': 'Mobile: Android',
        'name': 'WebView JavaScript Enabled',
        'severity': 'HIGH',
        'pattern': r'(setJavaScriptEnabled\s*\(\s*true\s*\)|webSettings\.javaScriptEnabled\s*=\s*true)',
        'description': 'WebView with JS enabled. If loading remote URLs, XSS possible.',
        'fix': 'Only enable JS if necessary. Whitelist URLs. Do not call addJavascriptInterface with remote URLs.',
        'langs': ['.java', '.kt'],
    },
    {
        'id': 'MOB-004',
        'category': 'Mobile: Android',
        'name': 'WebView File Access Enabled',
        'severity': 'CRITICAL',
        'pattern': r'(setAllowFileAccess\s*\(\s*true\s*\)|setAllowFileAccessFromFileURLs\s*\(\s*true\s*\))',
        'description': 'WebView file access enabled. Local file exfiltration possible.',
        'fix': 'Set setAllowFileAccess(false) and setAllowFileAccessFromFileURLs(false).',
        'langs': ['.java', '.kt'],
    },
    {
        'id': 'MOB-005',
        'category': 'Mobile: Android',
        'name': 'Insecure SharedPreferences Storage',
        'severity': 'HIGH',
        'pattern': r'(getSharedPreferences|SharedPreferences)\s*.*\.(putString|putInt|edit)\s*\(["\'].*(password|token|secret|key|auth)',
        'description': 'Sensitive data stored in SharedPreferences (plaintext on device).',
        'fix': 'Use Android Keystore + EncryptedSharedPreferences for sensitive data.',
        'langs': ['.java', '.kt'],
    },
    {
        'id': 'MOB-006',
        'category': 'Mobile: Android',
        'name': 'World-Readable/Writable File',
        'severity': 'HIGH',
        'pattern': r'(MODE_WORLD_READABLE|MODE_WORLD_WRITEABLE)',
        'description': 'File created with world-readable/writable mode. Other apps can access it.',
        'fix': 'Use MODE_PRIVATE. Share files with FileProvider instead.',
        'langs': ['.java', '.kt'],
    },
    {
        'id': 'MOB-007',
        'category': 'Mobile: Android',
        'name': 'Hardcoded API Key in Android Code',
        'severity': 'CRITICAL',
        'pattern': r'(BuildConfig\.|getString\(R\.string\.).*[Kk]ey|val\s+\w*[Kk]ey\s*=\s*["\'][A-Za-z0-9_\-]{16,}["\']',
        'description': 'API key hardcoded in Android source. Extractable from APK via decompilation.',
        'fix': 'Use remote config, certificate pinning + server-side proxy, or Android Keystore.',
        'langs': ['.java', '.kt'],
    },
    {
        'id': 'MOB-008',
        'category': 'Mobile: Android',
        'name': 'Debuggable APK',
        'severity': 'HIGH',
        'pattern': r'android:debuggable=["\']true["\']',
        'description': 'App is debuggable. Attacker can attach debugger, extract data, modify runtime behavior.',
        'fix': 'Set android:debuggable="false" or remove (false is default for release builds).',
        'langs': ['.xml'],
    },
    {
        'id': 'MOB-009',
        'category': 'Mobile: Android',
        'name': 'Backup Allowed',
        'severity': 'MEDIUM',
        'pattern': r'android:allowBackup=["\']true["\']',
        'description': 'App data backed up to cloud/USB. Physical access can restore sensitive app data.',
        'fix': 'Set android:allowBackup="false" or configure backup rules to exclude sensitive data.',
        'langs': ['.xml'],
    },
    {
        'id': 'MOB-010',
        'category': 'Mobile: Android',
        'name': 'SQLite Database Not Encrypted',
        'severity': 'HIGH',
        'pattern': r'(SQLiteDatabase|SQLiteOpenHelper|Room|@Database)',
        'negative_pattern': r'(SQLCipher|EncryptedDatabase|passphrase|encrypt)',
        'description': 'SQLite database without encryption. Accessible on rooted devices.',
        'fix': 'Use SQLCipher or Room with Android Keystore-protected encryption.',
        'langs': ['.java', '.kt'],
    },
    {
        'id': 'MOB-011',
        'category': 'Mobile: Android',
        'name': 'Implicit Intent for Sensitive Action',
        'severity': 'MEDIUM',
        'pattern': r'(Intent\(\)|new Intent\(\))\s*(?!.*setPackage|.*setClass)',
        'description': 'Implicit intent used for sensitive action. Can be intercepted by malicious apps.',
        'fix': 'Use explicit intents with setPackage() or setClass() for sensitive communications.',
        'langs': ['.java', '.kt'],
    },
    {
        'id': 'MOB-012',
        'category': 'Mobile: Android',
        'name': 'No Certificate Pinning',
        'severity': 'MEDIUM',
        'pattern': r'(OkHttpClient|HttpsURLConnection|Volley)',
        'negative_pattern': r'(CertificatePinner|certificatePinner|network_security_config|pin-set)',
        'description': 'Network client without certificate pinning. MITM with custom CA possible.',
        'fix': 'Implement certificate pinning with OkHttp CertificatePinner or network_security_config.xml.',
        'langs': ['.java', '.kt'],
    },
    {
        'id': 'MOB-013',
        'category': 'Mobile: Android',
        'name': 'Log Statements in Release Code',
        'severity': 'MEDIUM',
        'pattern': r'(Log\.(d|i|v|w|e)\s*\(|System\.out\.println)',
        'description': 'Log statements leak sensitive information in production builds.',
        'fix': 'Use ProGuard to strip logs, or wrap in BuildConfig.DEBUG checks.',
        'langs': ['.java', '.kt'],
    },

    # ─────────────────────────────────────────────
    # iOS / SWIFT / OBJECTIVE-C
    # ─────────────────────────────────────────────
    {
        'id': 'MOB-020',
        'category': 'Mobile: iOS',
        'name': 'NSUserDefaults for Sensitive Data',
        'severity': 'HIGH',
        'pattern': r'UserDefaults\.(standard\.)?(set|setValue)\s*\(.*\b(password|token|secret|key|auth)\b',
        'description': 'Sensitive data stored in NSUserDefaults (plaintext in plist). Backed up to iCloud.',
        'fix': 'Use iOS Keychain Services for sensitive data storage.',
        'langs': ['.swift', '.m'],
    },
    {
        'id': 'MOB-021',
        'category': 'Mobile: iOS',
        'name': 'ATS Exception - Arbitrary Loads',
        'severity': 'HIGH',
        'pattern': r'NSAllowsArbitraryLoads\s*</?\s*key\s*>.*<true\s*/>',
        'description': 'App Transport Security disabled. Allows unencrypted HTTP connections.',
        'fix': 'Remove NSAllowsArbitraryLoads. Add specific domain exceptions only if absolutely needed.',
        'langs': ['.plist', '.xml'],
    },
    {
        'id': 'MOB-022',
        'category': 'Mobile: iOS',
        'name': 'Keychain Item Without Accessibility Restriction',
        'severity': 'MEDIUM',
        'pattern': r'kSecAttrAccessible\w*AfterFirstUnlockThisDeviceOnly|kSecAttrAccessibleAlways\b',
        'description': 'Keychain item accessible when device is locked or without device restriction.',
        'fix': 'Use kSecAttrAccessibleWhenUnlockedThisDeviceOnly for most sensitive items.',
        'langs': ['.swift', '.m'],
    },
    {
        'id': 'MOB-023',
        'category': 'Mobile: iOS',
        'name': 'No Jailbreak Detection',
        'severity': 'LOW',
        'pattern': r'(UIApplication\.shared\.canOpenURL|FileManager\.default\.fileExists)',
        'negative_pattern': r'(jailbreak|jail_break|isJailbroken|cydia|substrate)',
        'description': 'App does not implement jailbreak detection. Security controls easier to bypass on jailbroken device.',
        'fix': 'Implement jailbreak detection using IOSSecuritySuite or custom checks.',
        'langs': ['.swift', '.m'],
    },
    {
        'id': 'MOB-024',
        'category': 'Mobile: iOS',
        'name': 'WKWebView JavaScript Bridge Without Validation',
        'severity': 'HIGH',
        'pattern': r'(addScriptMessageHandler|evaluateJavaScript|WKScriptMessageHandler)',
        'negative_pattern': r'(validate|sanitize|whitelist|allowedOrigins)',
        'description': 'WKWebView JS bridge without origin or content validation.',
        'fix': 'Validate all messages received through script message handler. Sanitize JS input.',
        'langs': ['.swift', '.m'],
    },
    {
        'id': 'MOB-025',
        'category': 'Mobile: iOS',
        'name': 'Hardcoded API Key in Swift',
        'severity': 'CRITICAL',
        'pattern': r'let\s+\w*(key|token|secret|apiKey)\s*=\s*["\'][A-Za-z0-9_\-]{16,}["\']',
        'description': 'API key hardcoded in Swift source. Extractable from IPA binary.',
        'fix': 'Use remote config or server-side proxy. Consider obfuscation as secondary measure only.',
        'langs': ['.swift'],
    },
    {
        'id': 'MOB-026',
        'category': 'Mobile: iOS',
        'name': 'No SSL Pinning',
        'severity': 'MEDIUM',
        'pattern': r'(URLSession|URLSessionConfiguration|Alamofire|AF\.request)',
        'negative_pattern': r'(pinnedCertificates|pinnedPublicKeys|ServerTrustPolicy|PinningMode)',
        'description': 'Network requests without SSL pinning. MITM with custom CA possible.',
        'fix': 'Implement certificate or public key pinning using TrustKit or Alamofire ServerTrustManager.',
        'langs': ['.swift', '.m'],
    },

    # ─────────────────────────────────────────────
    # FLUTTER / DART
    # ─────────────────────────────────────────────
    {
        'id': 'MOB-030',
        'category': 'Mobile: Flutter',
        'name': 'Flutter SharedPreferences for Sensitive Data',
        'severity': 'HIGH',
        'pattern': r'SharedPreferences\.(getInstance|setString|setInt).*\b(password|token|secret|key|auth)\b',
        'description': 'Sensitive data in Flutter SharedPreferences (plaintext storage).',
        'fix': 'Use flutter_secure_storage package which uses Keychain/Keystore.',
        'langs': ['.dart'],
    },
    {
        'id': 'MOB-031',
        'category': 'Mobile: Flutter',
        'name': 'Flutter HTTP Without Security',
        'severity': 'HIGH',
        'pattern': r'http\.get\s*\(Uri\.parse\s*\(["\']http://',
        'description': 'Flutter HTTP client using unencrypted HTTP URL.',
        'fix': 'Use HTTPS. Implement certificate pinning with http package or dio with custom HttpClient.',
        'langs': ['.dart'],
    },

    # ─────────────────────────────────────────────
    # REACT NATIVE
    # ─────────────────────────────────────────────
    {
        'id': 'MOB-040',
        'category': 'Mobile: React Native',
        'name': 'AsyncStorage for Sensitive Data',
        'severity': 'HIGH',
        'pattern': r'AsyncStorage\.(setItem|getItem).*\b(password|token|secret|key|auth)\b',
        'description': 'React Native AsyncStorage is unencrypted. Sensitive data exposed on rooted devices.',
        'fix': 'Use react-native-keychain or react-native-sensitive-info for secure storage.',
        'langs': ['.js', '.ts', '.jsx', '.tsx'],
    },
    {
        'id': 'MOB-041',
        'category': 'Mobile: React Native',
        'name': 'Hardcoded API Keys in RN Code',
        'severity': 'CRITICAL',
        'pattern': r'const\s+\w*(KEY|TOKEN|SECRET|API)\s*=\s*["\'][A-Za-z0-9_\-]{16,}["\']',
        'description': 'API key hardcoded in React Native code. Bundled in the app binary.',
        'fix': 'Use react-native-config with .env files. Never commit .env. Use server-side proxy for sensitive APIs.',
        'langs': ['.js', '.ts', '.jsx', '.tsx'],
    },
]
