"""
OWASP Top 10 (2021) Security Patterns
A01-A10 comprehensive regex-based checks for all languages.
"""

OWASP_PATTERNS = [

    # ─────────────────────────────────────────────
    # A01: BROKEN ACCESS CONTROL
    # ─────────────────────────────────────────────
    {
        'id': 'A01-001',
        'category': 'A01: Broken Access Control',
        'name': 'Missing Authorization Decorator',
        'severity': 'HIGH',
        'pattern': r'@app\.route\(.+\)\s*\ndef\s+\w+\(',
        'negative_pattern': r'@login_required|@require_auth|@permission_required|@jwt_required|@auth\.login_required',
        'description': 'Route defined without any authorization decorator. Anyone can access this endpoint.',
        'fix': 'Add @login_required, @jwt_required, or equivalent auth decorator before the route function.',
        'langs': ['.py'],
        'owasp': 'A01:2021',
        'cwe': 'CWE-862',
    },
    {
        'id': 'A01-002',
        'category': 'A01: Broken Access Control',
        'name': 'IDOR - Direct Object Reference',
        'severity': 'HIGH',
        'pattern': r'(user_id|account_id|file_id|order_id)\s*=\s*request\.(args|form|json|data|GET|POST)\[',
        'description': 'Direct use of user-supplied ID without ownership verification (IDOR).',
        'fix': 'Always verify that the requesting user owns or has permission to access the requested object.',
        'langs': ['.py', '.js', '.ts', '.php', '.rb'],
        'owasp': 'A01:2021',
        'cwe': 'CWE-639',
    },
    {
        'id': 'A01-003',
        'category': 'A01: Broken Access Control',
        'name': 'Directory Traversal',
        'severity': 'CRITICAL',
        'pattern': r'(open|file|read_file|send_file|readFile|fopen)\s*\(\s*(request|req|params|query|body|user_input|input)',
        'description': 'File operation using unsanitized user input. Path traversal (../../../etc/passwd) possible.',
        'fix': 'Use os.path.basename(), realpath() and validate the path is within allowed directory.',
        'langs': ['.py', '.js', '.ts', '.php', '.rb', '.java'],
        'owasp': 'A01:2021',
        'cwe': 'CWE-22',
    },
    {
        'id': 'A01-004',
        'category': 'A01: Broken Access Control',
        'name': 'CORS Wildcard',
        'severity': 'HIGH',
        'pattern': r'(Access-Control-Allow-Origin|allow_origins|cors_origins)\s*[=:]\s*["\']?\*["\']?',
        'description': 'CORS set to wildcard (*). Any origin can make credentialed requests.',
        'fix': 'Restrict CORS to specific trusted origins. Never combine wildcard with allow_credentials=True.',
        'langs': ['.py', '.js', '.ts', '.java', '.go', '.rb', '.php', '.yml', '.yaml'],
        'owasp': 'A01:2021',
        'cwe': 'CWE-942',
    },
    {
        'id': 'A01-005',
        'category': 'A01: Broken Access Control',
        'name': 'Admin Route Without Role Check',
        'severity': 'CRITICAL',
        'pattern': r'(/admin|/superuser|/dashboard/admin|/management)',
        'negative_pattern': r'(role|is_admin|admin_required|is_superuser|has_permission)',
        'description': 'Admin route detected without visible role/permission check.',
        'fix': 'Ensure all admin routes check user role before granting access.',
        'langs': ['.py', '.js', '.ts', '.java', '.php', '.rb', '.go'],
        'owasp': 'A01:2021',
        'cwe': 'CWE-285',
    },

    # ─────────────────────────────────────────────
    # A02: CRYPTOGRAPHIC FAILURES
    # ─────────────────────────────────────────────
    {
        'id': 'A02-001',
        'category': 'A02: Cryptographic Failures',
        'name': 'Weak Hashing Algorithm - MD5',
        'severity': 'HIGH',
        'pattern': r'\b(md5|MD5|hashlib\.md5|MessageDigest\.getInstance\(["\']MD5["\']\))',
        'description': 'MD5 is cryptographically broken. Not suitable for passwords or integrity checks.',
        'fix': 'Use SHA-256 or SHA-3 for checksums. Use bcrypt/argon2/scrypt for passwords.',
        'langs': ['.py', '.js', '.ts', '.java', '.php', '.rb', '.go', '.c', '.cpp'],
        'owasp': 'A02:2021',
        'cwe': 'CWE-327',
    },
    {
        'id': 'A02-002',
        'category': 'A02: Cryptographic Failures',
        'name': 'Weak Hashing Algorithm - SHA1',
        'severity': 'HIGH',
        'pattern': r'\b(sha1|SHA1|sha-1|SHA-1|hashlib\.sha1|DigestAlgorithm\.SHA1)',
        'description': 'SHA-1 is deprecated and vulnerable to collision attacks.',
        'fix': 'Upgrade to SHA-256, SHA-384, or SHA-512.',
        'langs': ['.py', '.js', '.ts', '.java', '.php', '.rb', '.go'],
        'owasp': 'A02:2021',
        'cwe': 'CWE-327',
    },
    {
        'id': 'A02-003',
        'category': 'A02: Cryptographic Failures',
        'name': 'Hardcoded Secret Key',
        'severity': 'CRITICAL',
        'pattern': r'(SECRET_KEY|secret_key|JWT_SECRET|jwt_secret|SIGNING_KEY)\s*=\s*["\'][a-zA-Z0-9_\-\.]{8,}["\']',
        'description': 'Secret key hardcoded in source code. Anyone with repo access can forge tokens/sessions.',
        'fix': 'Load secrets from environment variables or a secrets manager (AWS Secrets Manager, HashiCorp Vault).',
        'langs': ['.py', '.js', '.ts', '.java', '.php', '.rb', '.go', '.env'],
        'owasp': 'A02:2021',
        'cwe': 'CWE-321',
    },
    {
        'id': 'A02-004',
        'category': 'A02: Cryptographic Failures',
        'name': 'Weak Encryption - DES/RC4/ECB',
        'severity': 'CRITICAL',
        'pattern': r'\b(DES|RC4|RC2|Blowfish|AES\.MODE_ECB|Cipher\.getInstance\(["\']AES/ECB)',
        'description': 'Weak or broken encryption algorithm in use. ECB mode is not semantically secure.',
        'fix': 'Use AES-256 in GCM mode. Never use ECB mode. RC4/DES are completely broken.',
        'langs': ['.py', '.java', '.js', '.ts', '.c', '.cpp', '.go', '.rb'],
        'owasp': 'A02:2021',
        'cwe': 'CWE-326',
    },
    {
        'id': 'A02-005',
        'category': 'A02: Cryptographic Failures',
        'name': 'HTTP Instead of HTTPS',
        'severity': 'HIGH',
        'pattern': r'["\']http://(?!localhost|127\.0\.0\.1|0\.0\.0\.0|::1)',
        'description': 'Plain HTTP URL in code. Traffic transmitted in cleartext, vulnerable to MITM.',
        'fix': 'Use HTTPS for all external communications. Enforce TLS 1.2+.',
        'langs': ['.py', '.js', '.ts', '.java', '.go', '.php', '.rb', '.dart', '.swift', '.kt'],
        'owasp': 'A02:2021',
        'cwe': 'CWE-319',
    },
    {
        'id': 'A02-006',
        'category': 'A02: Cryptographic Failures',
        'name': 'Insecure Random Number',
        'severity': 'MEDIUM',
        'pattern': r'\b(random\.random|random\.randint|Math\.random\(\)|rand\(\)|srand\()',
        'description': 'Non-cryptographic random number generator used. Predictable for security-critical operations.',
        'fix': 'Use secrets.token_hex() (Python), crypto.randomBytes() (Node.js), or SecureRandom (Java) for tokens, OTPs, keys.',
        'langs': ['.py', '.js', '.ts', '.java', '.c', '.cpp', '.php'],
        'owasp': 'A02:2021',
        'cwe': 'CWE-338',
    },
    {
        'id': 'A02-007',
        'category': 'A02: Cryptographic Failures',
        'name': 'SSL/TLS Verification Disabled',
        'severity': 'CRITICAL',
        'pattern': r'(verify\s*=\s*False|ssl_verify\s*=\s*False|NODE_TLS_REJECT_UNAUTHORIZED\s*=\s*["\']0["\']|rejectUnauthorized\s*:\s*false|InsecureRequestWarning|CERT_NONE|checkCertificate\s*=\s*false)',
        'description': 'TLS/SSL certificate verification disabled. Vulnerable to man-in-the-middle attacks.',
        'fix': 'Never disable SSL verification in production. If using self-signed certs, bundle the CA instead.',
        'langs': ['.py', '.js', '.ts', '.java', '.go', '.rb', '.dart', '.swift', '.kt'],
        'owasp': 'A02:2021',
        'cwe': 'CWE-295',
    },

    # ─────────────────────────────────────────────
    # A03: INJECTION
    # ─────────────────────────────────────────────
    {
        'id': 'A03-001',
        'category': 'A03: Injection',
        'name': 'SQL Injection - String Formatting',
        'severity': 'CRITICAL',
        'pattern': r'(execute|query|cursor\.execute|db\.query)\s*\(\s*["\'].*(%s|%d|\{.*\}|"\s*\+|f")',
        'description': 'SQL query built with string formatting/concatenation. Classic SQL injection vector.',
        'fix': 'Use parameterized queries: cursor.execute("SELECT * FROM users WHERE id = %s", (user_id,))',
        'langs': ['.py', '.php', '.rb', '.java', '.js', '.ts', '.go'],
        'owasp': 'A03:2021',
        'cwe': 'CWE-89',
    },
    {
        'id': 'A03-002',
        'category': 'A03: Injection',
        'name': 'SQL Injection - Raw Query with User Input',
        'severity': 'CRITICAL',
        'pattern': r'(raw\(|RawSQL|\.objects\.raw|QuerySet\.extra|execute\(f["\']|cursor\.execute\(f["\'])',
        'description': 'Raw SQL execution with possible f-string injection.',
        'fix': 'Use Django ORM, SQLAlchemy, or parameterized queries.',
        'langs': ['.py'],
        'owasp': 'A03:2021',
        'cwe': 'CWE-89',
    },
    {
        'id': 'A03-003',
        'category': 'A03: Injection',
        'name': 'Command Injection',
        'severity': 'CRITICAL',
        'pattern': r'(os\.system|subprocess\.call|subprocess\.Popen|exec\(|eval\(|shell=True|child_process\.exec\b|Runtime\.getRuntime\(\)\.exec)',
        'description': 'Shell command execution with possible user input injection.',
        'fix': 'Use subprocess with list args and shell=False. Never pass user input directly to shell commands.',
        'langs': ['.py', '.js', '.ts', '.java', '.rb', '.php'],
        'owasp': 'A03:2021',
        'cwe': 'CWE-78',
    },
    {
        'id': 'A03-004',
        'category': 'A03: Injection',
        'name': 'eval() Usage',
        'severity': 'CRITICAL',
        'pattern': r'\beval\s*\(',
        'description': 'eval() executes arbitrary code. Extremely dangerous with any user input.',
        'fix': 'Remove eval(). Use ast.literal_eval() for data parsing, or JSON.parse() for JSON.',
        'langs': ['.py', '.js', '.ts', '.php', '.rb'],
        'owasp': 'A03:2021',
        'cwe': 'CWE-95',
    },
    {
        'id': 'A03-005',
        'category': 'A03: Injection',
        'name': 'XSS - innerHTML / dangerouslySetInnerHTML',
        'severity': 'HIGH',
        'pattern': r'(innerHTML\s*=|outerHTML\s*=|dangerouslySetInnerHTML|document\.write\(|\.html\()',
        'description': 'Unescaped HTML insertion. XSS (Cross-Site Scripting) vector.',
        'fix': 'Use textContent instead of innerHTML. Sanitize with DOMPurify before any HTML insertion.',
        'langs': ['.js', '.ts', '.jsx', '.tsx', '.html'],
        'owasp': 'A03:2021',
        'cwe': 'CWE-79',
    },
    {
        'id': 'A03-006',
        'category': 'A03: Injection',
        'name': 'LDAP Injection',
        'severity': 'HIGH',
        'pattern': r'(ldap_search|ldap\.search|ldap_bind|DirectorySearcher|LdapConnection)\s*\(.*\+',
        'description': 'LDAP query with string concatenation. LDAP injection possible.',
        'fix': 'Use parameterized LDAP queries or escape special characters (*, (, ), \\, NUL).',
        'langs': ['.py', '.java', '.js', '.ts', '.php', '.cs'],
        'owasp': 'A03:2021',
        'cwe': 'CWE-90',
    },
    {
        'id': 'A03-007',
        'category': 'A03: Injection',
        'name': 'XML External Entity (XXE)',
        'severity': 'HIGH',
        'pattern': r'(etree\.parse|lxml\.etree|xml\.etree|DocumentBuilder|SAXParser|XMLReader|parseXML)',
        'negative_pattern': r'(resolve_entities\s*=\s*False|XMLParser\(resolve_entities=False\)|FEATURE_EXTERNAL_GENERAL_ENTITIES)',
        'description': 'XML parser without XXE protection. External entity injection possible.',
        'fix': 'Disable external entity processing: etree.XMLParser(resolve_entities=False)',
        'langs': ['.py', '.java', '.js', '.ts', '.php', '.cs'],
        'owasp': 'A03:2021',
        'cwe': 'CWE-611',
    },
    {
        'id': 'A03-008',
        'category': 'A03: Injection',
        'name': 'NoSQL Injection',
        'severity': 'HIGH',
        'pattern': r'(\$where|\$regex|\$ne|\$gt|\$lt|\$in)\s*:.*request|collection\.find\(\{.*request',
        'description': 'MongoDB/NoSQL operator in query with user input. NoSQL injection possible.',
        'fix': 'Sanitize user input before using in MongoDB queries. Use mongoose schemas with strict mode.',
        'langs': ['.js', '.ts', '.py'],
        'owasp': 'A03:2021',
        'cwe': 'CWE-943',
    },
    {
        'id': 'A03-009',
        'category': 'A03: Injection',
        'name': 'Template Injection (SSTI)',
        'severity': 'CRITICAL',
        'pattern': r'(render_template_string|Template\(.*request|Environment\(\)\.from_string\(|\.render\(.*request)',
        'description': 'Server-Side Template Injection. Attacker can execute arbitrary code via template syntax.',
        'fix': 'Never pass user input directly to template engines. Use render_template() with fixed template files.',
        'langs': ['.py', '.js', '.ts', '.php', '.rb', '.java'],
        'owasp': 'A03:2021',
        'cwe': 'CWE-94',
    },
    {
        'id': 'A03-010',
        'category': 'A03: Injection',
        'name': 'Prompt Injection (LLM)',
        'severity': 'HIGH',
        'pattern': r'(prompt\s*=.*request|messages\s*=.*user_input|f["\'].*{user|f["\'].*{prompt|system_prompt.*\+)',
        'description': 'User input directly injected into LLM prompt. Prompt injection/jailbreak possible.',
        'fix': 'Sanitize user input before adding to prompts. Use system/user role separation. Add guardrails.',
        'langs': ['.py', '.js', '.ts'],
        'owasp': 'A03:2021',
        'cwe': 'CWE-20',
    },

    # ─────────────────────────────────────────────
    # A04: INSECURE DESIGN
    # ─────────────────────────────────────────────
    {
        'id': 'A04-001',
        'category': 'A04: Insecure Design',
        'name': 'No Rate Limiting on Auth Endpoints',
        'severity': 'HIGH',
        'pattern': r'@app\.route\(["\'].*(login|signin|auth|token|register|forgot.password).*["\']',
        'negative_pattern': r'(rate_limit|throttle|RateLimit|Throttle|limiter|slowapi)',
        'description': 'Authentication endpoint without rate limiting. Brute-force attacks possible.',
        'fix': 'Add rate limiting: flask-limiter, django-ratelimit, or API gateway rate limits.',
        'langs': ['.py', '.js', '.ts'],
        'owasp': 'A04:2021',
        'cwe': 'CWE-307',
    },
    {
        'id': 'A04-002',
        'category': 'A04: Insecure Design',
        'name': 'Missing Input Validation',
        'severity': 'MEDIUM',
        'pattern': r'(request\.json\[|request\.form\[|req\.body\.|params\[|query\[)(?!.*validate|.*schema|.*sanitize)',
        'description': 'User input used without explicit validation or schema check.',
        'fix': 'Use Pydantic, Marshmallow, Joi, Zod or similar validation library for all user inputs.',
        'langs': ['.py', '.js', '.ts'],
        'owasp': 'A04:2021',
        'cwe': 'CWE-20',
    },

    # ─────────────────────────────────────────────
    # A05: SECURITY MISCONFIGURATION
    # ─────────────────────────────────────────────
    {
        'id': 'A05-001',
        'category': 'A05: Security Misconfiguration',
        'name': 'Debug Mode Enabled',
        'severity': 'HIGH',
        'pattern': r'(DEBUG\s*=\s*True|debug\s*=\s*true|app\.run\(.*debug\s*=\s*True|NODE_ENV\s*=\s*["\']development["\'])',
        'description': 'Debug mode enabled. Exposes stack traces, internal paths, and sometimes interactive debugger.',
        'fix': 'Set DEBUG=False in production. Use environment variables to control debug mode.',
        'langs': ['.py', '.js', '.ts', '.env', '.yaml', '.yml'],
        'owasp': 'A05:2021',
        'cwe': 'CWE-94',
    },
    {
        'id': 'A05-002',
        'category': 'A05: Security Misconfiguration',
        'name': 'Missing Security Headers',
        'severity': 'MEDIUM',
        'pattern': r'(app\.run\(|listen\(|createServer\()',
        'negative_pattern': r'(helmet|Content-Security-Policy|X-Frame-Options|X-Content-Type-Options|Strict-Transport-Security)',
        'description': 'Web server started without security headers middleware.',
        'fix': 'Add helmet (Node.js) or Flask-Talisman (Python). Set CSP, HSTS, X-Frame-Options, etc.',
        'langs': ['.py', '.js', '.ts'],
        'owasp': 'A05:2021',
        'cwe': 'CWE-693',
    },
    {
        'id': 'A05-003',
        'category': 'A05: Security Misconfiguration',
        'name': 'Default Credentials',
        'severity': 'CRITICAL',
        'pattern': r'(password|passwd|pwd)\s*[=:]\s*["\']+(admin|password|123456|test|root|default|changeme|secret|pass|1234|qwerty)["\']',
        'description': 'Default or weak credentials hardcoded in source.',
        'fix': 'Remove all hardcoded credentials. Use environment variables and require strong passwords.',
        'langs': ['.py', '.js', '.ts', '.java', '.php', '.rb', '.go', '.yaml', '.yml', '.json'],
        'owasp': 'A05:2021',
        'cwe': 'CWE-798',
    },
    {
        'id': 'A05-004',
        'category': 'A05: Security Misconfiguration',
        'name': 'Insecure Cookie Configuration',
        'severity': 'HIGH',
        'pattern': r'(set_cookie|response\.set_cookie|cookie\(|res\.cookie)\s*\([^)]+\)',
        'negative_pattern': r'(httponly\s*=\s*true|secure\s*=\s*true|samesite|HttpOnly|Secure)',
        'description': 'Cookie set without HttpOnly/Secure/SameSite flags.',
        'fix': 'Set cookies with: HttpOnly=True, Secure=True, SameSite=Strict/Lax.',
        'langs': ['.py', '.js', '.ts', '.php', '.rb', '.java'],
        'owasp': 'A05:2021',
        'cwe': 'CWE-614',
    },
    {
        'id': 'A05-005',
        'category': 'A05: Security Misconfiguration',
        'name': 'Exposed Stack Trace to Client',
        'severity': 'MEDIUM',
        'pattern': r'(traceback\.print_exc\(\)|traceback\.format_exc\(\)|err\.stack|error\.stack|exception\.getMessage\(\))\s*.*response|return.*traceback',
        'description': 'Stack trace returned to client. Exposes internal implementation details.',
        'fix': 'Log stack traces server-side only. Return generic error messages to clients.',
        'langs': ['.py', '.js', '.ts', '.java', '.php'],
        'owasp': 'A05:2021',
        'cwe': 'CWE-209',
    },

    # ─────────────────────────────────────────────
    # A06: VULNERABLE & OUTDATED COMPONENTS
    # ─────────────────────────────────────────────
    {
        'id': 'A06-001',
        'category': 'A06: Vulnerable Components',
        'name': 'Unpinned Dependencies',
        'severity': 'MEDIUM',
        'pattern': r'"[a-z@][a-zA-Z0-9\-_/]+"\s*:\s*"\*"',
        'description': 'Wildcard (*) dependency version. Automatically installs latest, potentially vulnerable versions.',
        'fix': 'Pin all dependency versions. Use package-lock.json or yarn.lock. Run npm audit regularly.',
        'langs': ['.json'],
        'owasp': 'A06:2021',
        'cwe': 'CWE-1104',
    },
    {
        'id': 'A06-002',
        'category': 'A06: Vulnerable Components',
        'name': 'No Dependency Lock File',
        'severity': 'LOW',
        'pattern': r'requirements\.txt',
        'negative_pattern': r'(==)',
        'description': 'Python requirements.txt without pinned versions.',
        'fix': 'Pin all versions: package==1.2.3. Use pip-compile or Poetry for lockfiles.',
        'langs': ['.txt'],
        'owasp': 'A06:2021',
        'cwe': 'CWE-1104',
    },

    # ─────────────────────────────────────────────
    # A07: IDENTIFICATION & AUTHENTICATION FAILURES
    # ─────────────────────────────────────────────
    {
        'id': 'A07-001',
        'category': 'A07: Auth Failures',
        'name': 'JWT - Algorithm None Attack',
        'severity': 'CRITICAL',
        'pattern': r'(jwt\.decode|verify\s*=\s*False|algorithms\s*=\s*\[.*none.*\]|algorithm\s*=\s*["\']none["\'])',
        'description': 'JWT decoded without algorithm verification or with "none" algorithm. Token forgery possible.',
        'fix': 'Always specify allowed algorithms: jwt.decode(token, key, algorithms=["HS256"]). Never allow "none".',
        'langs': ['.py', '.js', '.ts', '.java', '.go'],
        'owasp': 'A07:2021',
        'cwe': 'CWE-347',
    },
    {
        'id': 'A07-002',
        'category': 'A07: Auth Failures',
        'name': 'Plaintext Password Storage',
        'severity': 'CRITICAL',
        'pattern': r'(password\s*=\s*request|password\s*=\s*data\[|\.save\(\).*password|INSERT.*password.*request)',
        'negative_pattern': r'(hash|bcrypt|argon2|scrypt|pbkdf2|make_password|set_password)',
        'description': 'Password stored without hashing. Data breach exposes all user passwords.',
        'fix': 'Use bcrypt, argon2, or scrypt. Never store plaintext passwords.',
        'langs': ['.py', '.js', '.ts', '.php', '.java', '.rb'],
        'owasp': 'A07:2021',
        'cwe': 'CWE-256',
    },
    {
        'id': 'A07-003',
        'category': 'A07: Auth Failures',
        'name': 'Weak JWT Secret',
        'severity': 'CRITICAL',
        'pattern': r'(jwt\.sign|jwt\.encode|create_access_token)\s*\(.*["\'][a-zA-Z0-9]{1,15}["\']',
        'description': 'JWT signed with a short/weak secret. Brute-force of HMAC secret possible.',
        'fix': 'Use a cryptographically random secret of at least 256 bits. Load from environment variable.',
        'langs': ['.py', '.js', '.ts', '.java'],
        'owasp': 'A07:2021',
        'cwe': 'CWE-521',
    },
    {
        'id': 'A07-004',
        'category': 'A07: Auth Failures',
        'name': 'Session Not Invalidated on Logout',
        'severity': 'HIGH',
        'pattern': r'def\s+logout|router\.(get|post)\s*\(["\'].*/logout',
        'negative_pattern': r'(session\.clear|session\.flush|session\.delete|blacklist|revoke|invalidate)',
        'description': 'Logout endpoint without session/token invalidation. Old tokens remain valid.',
        'fix': 'On logout: clear server-side session, add JWT to blacklist, or rotate refresh tokens.',
        'langs': ['.py', '.js', '.ts', '.java', '.php', '.rb'],
        'owasp': 'A07:2021',
        'cwe': 'CWE-613',
    },

    # ─────────────────────────────────────────────
    # A08: SOFTWARE & DATA INTEGRITY FAILURES
    # ─────────────────────────────────────────────
    {
        'id': 'A08-001',
        'category': 'A08: Integrity Failures',
        'name': 'Insecure Deserialization - Pickle',
        'severity': 'CRITICAL',
        'pattern': r'(pickle\.loads|pickle\.load|cPickle\.loads|marshal\.loads|shelve\.open)',
        'description': 'Pickle deserialization of untrusted data leads to Remote Code Execution.',
        'fix': 'Never deserialize untrusted data with pickle. Use JSON, msgpack, or protobuf instead.',
        'langs': ['.py'],
        'owasp': 'A08:2021',
        'cwe': 'CWE-502',
    },
    {
        'id': 'A08-002',
        'category': 'A08: Integrity Failures',
        'name': 'Insecure Deserialization - Java',
        'severity': 'CRITICAL',
        'pattern': r'(ObjectInputStream|readObject\(\)|XMLDecoder|XStream\.fromXML|JsonSlurper)',
        'description': 'Java deserialization of untrusted data. RCE gadget chains possible.',
        'fix': 'Use serialization filters (Java 9+), or replace with JSON/protobuf deserialization.',
        'langs': ['.java'],
        'owasp': 'A08:2021',
        'cwe': 'CWE-502',
    },
    {
        'id': 'A08-003',
        'category': 'A08: Integrity Failures',
        'name': 'YAML Unsafe Load',
        'severity': 'CRITICAL',
        'pattern': r'yaml\.load\s*\((?!.*Loader=yaml\.SafeLoader|.*Loader=yaml\.BaseLoader)',
        'description': 'yaml.load() without SafeLoader executes arbitrary Python code.',
        'fix': 'Use yaml.safe_load() or yaml.load(data, Loader=yaml.SafeLoader).',
        'langs': ['.py'],
        'owasp': 'A08:2021',
        'cwe': 'CWE-502',
    },

    # ─────────────────────────────────────────────
    # A09: SECURITY LOGGING & MONITORING FAILURES
    # ─────────────────────────────────────────────
    {
        'id': 'A09-001',
        'category': 'A09: Logging Failures',
        'name': 'Sensitive Data in Logs',
        'severity': 'HIGH',
        'pattern': r'(log|logger|print|console\.log|logging)\s*.*\b(password|passwd|token|secret|credit_card|ssn|api_key|private_key)',
        'description': 'Sensitive data being logged. Log files can expose credentials/PII.',
        'fix': 'Never log passwords, tokens, or PII. Mask sensitive fields before logging.',
        'langs': ['.py', '.js', '.ts', '.java', '.go', '.rb', '.php'],
        'owasp': 'A09:2021',
        'cwe': 'CWE-532',
    },
    {
        'id': 'A09-002',
        'category': 'A09: Logging Failures',
        'name': 'No Error Logging',
        'severity': 'LOW',
        'pattern': r'except\s*(\w+\s*)?:\s*\n\s*(pass|return|continue)',
        'description': 'Exception silently swallowed without logging. Security events go undetected.',
        'fix': 'Log all exceptions with context. Use structured logging (JSON) for better analysis.',
        'langs': ['.py'],
        'owasp': 'A09:2021',
        'cwe': 'CWE-390',
    },

    # ─────────────────────────────────────────────
    # A10: SERVER-SIDE REQUEST FORGERY (SSRF)
    # ─────────────────────────────────────────────
    {
        'id': 'A10-001',
        'category': 'A10: SSRF',
        'name': 'SSRF - Unvalidated URL Fetch',
        'severity': 'HIGH',
        'pattern': r'(requests\.get|requests\.post|urllib\.request|fetch\(|axios\.get|axios\.post|httpx\.get)\s*\(.*\b(request|req|params|query|body|url|href)\b',
        'description': 'HTTP request to URL derived from user input. SSRF attack possible.',
        'fix': 'Whitelist allowed URLs/domains. Block requests to internal IPs (10.x, 172.16.x, 192.168.x, 169.254.x).',
        'langs': ['.py', '.js', '.ts', '.java', '.go', '.php', '.rb'],
        'owasp': 'A10:2021',
        'cwe': 'CWE-918',
    },
    {
        'id': 'A10-002',
        'category': 'A10: SSRF',
        'name': 'Open Redirect',
        'severity': 'MEDIUM',
        'pattern': r'(redirect\(|HttpResponseRedirect\(|res\.redirect\(|response\.redirect_to)\s*.*\b(request|params|query|url|next|redirect_url)\b',
        'description': 'Redirect to URL from user input without validation. Open redirect / phishing vector.',
        'fix': 'Validate redirect URLs against an allowlist of trusted domains.',
        'langs': ['.py', '.js', '.ts', '.java', '.php', '.rb'],
        'owasp': 'A10:2021',
        'cwe': 'CWE-601',
    },
]
