"""
CI/CD Pipeline, DevOps, Docker, Kubernetes, Terraform Security Patterns.
"""

PIPELINE_PATTERNS = [

    # ─────────────────────────────────────────────
    # DOCKER
    # ─────────────────────────────────────────────
    {
        'id': 'PIPE-001',
        'category': 'Pipeline: Docker',
        'name': 'Running as Root in Container',
        'severity': 'HIGH',
        'pattern': r'^(USER root|USER 0)',
        'description': 'Container running as root. Privilege escalation to host if container is breached.',
        'fix': 'Add: USER nonroot (after installing packages). Use non-privileged user.',
        'langs': ['Dockerfile'],
    },
    {
        'id': 'PIPE-002',
        'category': 'Pipeline: Docker',
        'name': 'No Non-Root User in Dockerfile',
        'severity': 'HIGH',
        'pattern': r'FROM\s+\w',
        'negative_pattern': r'(USER\s+(?!root|0)\w)',
        'description': 'Dockerfile does not switch to non-root user. Container runs as root by default.',
        'fix': 'Add near end of Dockerfile: RUN useradd -r appuser && USER appuser',
        'langs': ['Dockerfile'],
    },
    {
        'id': 'PIPE-003',
        'category': 'Pipeline: Docker',
        'name': 'Secrets in Dockerfile ENV',
        'severity': 'CRITICAL',
        'pattern': r'ENV\s+\w*(PASSWORD|SECRET|KEY|TOKEN|API_KEY)\s*=\s*\S+',
        'description': 'Secret passed as ENV variable in Dockerfile. Visible in docker inspect and image layers.',
        'fix': 'Use Docker BuildKit secrets: --mount=type=secret. Never put secrets in ENV or ARG.',
        'langs': ['Dockerfile'],
    },
    {
        'id': 'PIPE-004',
        'category': 'Pipeline: Docker',
        'name': 'Secrets in Docker ARG',
        'severity': 'CRITICAL',
        'pattern': r'ARG\s+\w*(PASSWORD|SECRET|KEY|TOKEN)',
        'description': 'Secret passed as build ARG. Stored in image history, visible with docker history.',
        'fix': 'Use Docker BuildKit --secret or external secrets manager. Never use ARG for secrets.',
        'langs': ['Dockerfile'],
    },
    {
        'id': 'PIPE-005',
        'category': 'Pipeline: Docker',
        'name': 'Unpinned Base Image',
        'severity': 'MEDIUM',
        'pattern': r'^FROM\s+[\w\-/]+:(latest|stable|main)',
        'description': 'Using :latest or non-specific tag. Unpredictable updates, potential supply chain attacks.',
        'fix': 'Pin to specific digest: FROM python@sha256:abc123 or specific version: python:3.11.4-slim',
        'langs': ['Dockerfile'],
    },
    {
        'id': 'PIPE-006',
        'category': 'Pipeline: Docker',
        'name': 'Privileged Container',
        'severity': 'CRITICAL',
        'pattern': r'privileged\s*:\s*true',
        'description': 'Container running in privileged mode. Full host system access, complete security bypass.',
        'fix': 'Remove privileged: true. Use specific capabilities instead: cap_add: [NET_ADMIN]',
        'langs': ['.yml', '.yaml'],
    },
    {
        'id': 'PIPE-007',
        'category': 'Pipeline: Docker',
        'name': 'Host Network Mode',
        'severity': 'HIGH',
        'pattern': r'network_mode\s*:\s*["\']?host["\']?',
        'description': 'Container sharing host network stack. Network isolation bypassed.',
        'fix': 'Use custom bridge networks instead. Only use host network mode if absolutely required.',
        'langs': ['.yml', '.yaml'],
    },
    {
        'id': 'PIPE-008',
        'category': 'Pipeline: Docker',
        'name': 'Docker Socket Mounted',
        'severity': 'CRITICAL',
        'pattern': r'/var/run/docker\.sock:/var/run/docker\.sock',
        'description': 'Docker socket mounted into container. Full host takeover via docker API.',
        'fix': 'Never mount Docker socket unless absolutely necessary (e.g., CI agents). Use alternatives.',
        'langs': ['.yml', '.yaml', 'Dockerfile'],
    },
    {
        'id': 'PIPE-009',
        'category': 'Pipeline: Docker',
        'name': 'No Health Check',
        'severity': 'LOW',
        'pattern': r'FROM\s+\w',
        'negative_pattern': r'HEALTHCHECK',
        'description': 'No HEALTHCHECK in Dockerfile. Unhealthy containers may stay in rotation.',
        'fix': 'Add: HEALTHCHECK --interval=30s CMD curl -f http://localhost/health || exit 1',
        'langs': ['Dockerfile'],
    },

    # ─────────────────────────────────────────────
    # KUBERNETES
    # ─────────────────────────────────────────────
    {
        'id': 'PIPE-010',
        'category': 'Pipeline: Kubernetes',
        'name': 'K8s Secret in Plain YAML',
        'severity': 'CRITICAL',
        'pattern': r'kind:\s*Secret.*\nmetadata:',
        'negative_pattern': r'(sealed-secrets|ExternalSecret|vault\.hashicorp|encrypted)',
        'description': 'Kubernetes Secret stored as base64 (not encrypted) in YAML file.',
        'fix': 'Use Sealed Secrets, External Secrets Operator, or Vault Agent Injector. Never commit plain K8s Secrets.',
        'langs': ['.yml', '.yaml'],
    },
    {
        'id': 'PIPE-011',
        'category': 'Pipeline: Kubernetes',
        'name': 'Container Running as Root in K8s',
        'severity': 'HIGH',
        'pattern': r'(runAsRoot\s*:\s*true|runAsUser\s*:\s*0)',
        'description': 'Kubernetes pod configured to run as root user.',
        'fix': 'Set securityContext: runAsNonRoot: true, runAsUser: 1000',
        'langs': ['.yml', '.yaml'],
    },
    {
        'id': 'PIPE-012',
        'category': 'Pipeline: Kubernetes',
        'name': 'Missing Resource Limits',
        'severity': 'MEDIUM',
        'pattern': r'containers:\s*\n\s*- name:',
        'negative_pattern': r'(resources:|limits:|requests:)',
        'description': 'K8s container without resource limits. One pod can starve the entire node.',
        'fix': 'Set resources.limits.cpu and resources.limits.memory for all containers.',
        'langs': ['.yml', '.yaml'],
    },
    {
        'id': 'PIPE-013',
        'category': 'Pipeline: Kubernetes',
        'name': 'AllowPrivilegeEscalation Not Disabled',
        'severity': 'HIGH',
        'pattern': r'securityContext:',
        'negative_pattern': r'allowPrivilegeEscalation\s*:\s*false',
        'description': 'Container allows privilege escalation. Compromised process can gain root.',
        'fix': 'Set securityContext.allowPrivilegeEscalation: false in all containers.',
        'langs': ['.yml', '.yaml'],
    },
    {
        'id': 'PIPE-014',
        'category': 'Pipeline: Kubernetes',
        'name': 'ClusterAdmin Role Binding',
        'severity': 'CRITICAL',
        'pattern': r'(clusterrole|ClusterRole)\s*.*cluster-admin',
        'description': 'Service account bound to cluster-admin role. Full cluster access.',
        'fix': 'Follow least privilege. Create specific RBAC roles with only needed permissions.',
        'langs': ['.yml', '.yaml'],
    },
    {
        'id': 'PIPE-015',
        'category': 'Pipeline: Kubernetes',
        'name': 'Readiness/Liveness Probe Missing',
        'severity': 'LOW',
        'pattern': r'containers:\s*\n\s*- name:',
        'negative_pattern': r'(livenessProbe|readinessProbe)',
        'description': 'Pod without health probes. Failed containers stay in service.',
        'fix': 'Define livenessProbe and readinessProbe for all production containers.',
        'langs': ['.yml', '.yaml'],
    },

    # ─────────────────────────────────────────────
    # GITHUB ACTIONS / CI-CD
    # ─────────────────────────────────────────────
    {
        'id': 'PIPE-020',
        'category': 'Pipeline: GitHub Actions',
        'name': 'Secrets in GitHub Actions Log',
        'severity': 'CRITICAL',
        'pattern': r'(echo\s+\$\{\{.*secrets\.|run:.*echo.*secrets\.)',
        'description': 'GitHub Actions secret being echoed to log. Visible in workflow run logs.',
        'fix': 'Never echo secrets. GitHub Actions masks known secrets but this is not reliable.',
        'langs': ['.yml', '.yaml'],
    },
    {
        'id': 'PIPE-021',
        'category': 'Pipeline: GitHub Actions',
        'name': 'Unpinned GitHub Action',
        'severity': 'HIGH',
        'pattern': r'uses:\s+[\w\-]+/[\w\-]+@(main|master|latest|v\d+)',
        'description': 'GitHub Action pinned to branch or major version, not commit SHA. Supply chain attack risk.',
        'fix': 'Pin actions to commit SHA: uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675',
        'langs': ['.yml', '.yaml'],
    },
    {
        'id': 'PIPE-022',
        'category': 'Pipeline: GitHub Actions',
        'name': 'GITHUB_TOKEN with Write Permissions',
        'severity': 'HIGH',
        'pattern': r'permissions:\s*\n\s*\w+:\s*write-all|permissions:\s*write-all',
        'description': 'Workflow has write-all permissions. Compromised workflow can push malicious code.',
        'fix': 'Set minimum required permissions. Use read-all as default and grant specific writes only.',
        'langs': ['.yml', '.yaml'],
    },
    {
        'id': 'PIPE-023',
        'category': 'Pipeline: GitHub Actions',
        'name': 'Pull Request Trigger Without Approval Gate',
        'severity': 'MEDIUM',
        'pattern': r'on:\s*\n\s*pull_request_target:',
        'description': 'pull_request_target trigger runs in privileged context. External PRs can exfiltrate secrets.',
        'fix': 'Use pull_request instead of pull_request_target. Add manual approval gate for external PRs.',
        'langs': ['.yml', '.yaml'],
    },
    {
        'id': 'PIPE-024',
        'category': 'Pipeline: GitHub Actions',
        'name': 'Script Injection via Context Variables',
        'severity': 'HIGH',
        'pattern': r'run:.*\$\{\{\s*(github\.event\.(issue|pull_request|comment)\.(body|title)|github\.head_ref)',
        'description': 'GitHub Actions script injection. User-controlled data used directly in shell run step.',
        'fix': 'Use environment variables to sanitize: env: VAR: ${{ github.event.issue.body }}',
        'langs': ['.yml', '.yaml'],
    },

    # ─────────────────────────────────────────────
    # TERRAFORM / INFRASTRUCTURE AS CODE
    # ─────────────────────────────────────────────
    {
        'id': 'PIPE-030',
        'category': 'Pipeline: Terraform',
        'name': 'Hardcoded Credentials in Terraform',
        'severity': 'CRITICAL',
        'pattern': r'(access_key|secret_key|password|private_key)\s*=\s*["\'][A-Za-z0-9_\-/+]{8,}["\']',
        'description': 'Credentials hardcoded in Terraform config. Committed to version control.',
        'fix': 'Use environment variables, AWS IAM roles, or Terraform Vault provider.',
        'langs': ['.tf', '.tfvars'],
    },
    {
        'id': 'PIPE-031',
        'category': 'Pipeline: Terraform',
        'name': 'S3 Bucket Public Access',
        'severity': 'CRITICAL',
        'pattern': r'(acl\s*=\s*["\']public-read|block_public_acls\s*=\s*false)',
        'description': 'S3 bucket configured with public access. Data exposure risk.',
        'fix': 'Set block_public_acls = true, block_public_policy = true, restrict_public_buckets = true.',
        'langs': ['.tf'],
    },
    {
        'id': 'PIPE-032',
        'category': 'Pipeline: Terraform',
        'name': 'Security Group Open to World',
        'severity': 'CRITICAL',
        'pattern': r'(cidr_blocks\s*=\s*\["0\.0\.0\.0/0"\]|ipv6_cidr_blocks\s*=\s*\["::/0"\])',
        'description': 'Security group rule allowing traffic from entire internet.',
        'fix': 'Restrict CIDR blocks to specific IPs or VPC CIDR. Never open 0.0.0.0/0 for sensitive ports.',
        'langs': ['.tf'],
    },
    {
        'id': 'PIPE-033',
        'category': 'Pipeline: Terraform',
        'name': 'Terraform State File Without Encryption',
        'severity': 'HIGH',
        'pattern': r'backend\s*["\']s3["\']',
        'negative_pattern': r'(encrypt\s*=\s*true)',
        'description': 'Terraform S3 backend without state file encryption.',
        'fix': 'Add encrypt = true to backend config. State files contain sensitive infrastructure details.',
        'langs': ['.tf'],
    },
    {
        'id': 'PIPE-034',
        'category': 'Pipeline: Terraform',
        'name': 'RDS Instance Publicly Accessible',
        'severity': 'CRITICAL',
        'pattern': r'publicly_accessible\s*=\s*true',
        'description': 'RDS database instance exposed to public internet.',
        'fix': 'Set publicly_accessible = false. Place in private subnet with VPC security groups.',
        'langs': ['.tf'],
    },

    # ─────────────────────────────────────────────
    # SUPPLY CHAIN
    # ─────────────────────────────────────────────
    {
        'id': 'PIPE-040',
        'category': 'Pipeline: Supply Chain',
        'name': 'Curl Pipe to Shell (Unsafe Install)',
        'severity': 'CRITICAL',
        'pattern': r'curl\s+.*\|\s*(bash|sh|zsh)',
        'description': 'curl | bash pattern. Remote code execution from untrusted source.',
        'fix': 'Download script, inspect it, verify checksum, then execute. Or use package manager.',
        'langs': ['.sh', 'Dockerfile', '.yml', '.yaml'],
    },
    {
        'id': 'PIPE-041',
        'category': 'Pipeline: Supply Chain',
        'name': 'Dependency from Non-Official Registry',
        'severity': 'MEDIUM',
        'pattern': r'(registry\.npmjs\.org|pypi\.org|--index-url\s+(?!https://pypi\.org)|npm install.*--registry)',
        'description': 'Package installed from non-official or custom registry without verification.',
        'fix': 'Use official registries. Enable subresource integrity. Audit packages with npm audit/safety.',
        'langs': ['.sh', 'Dockerfile', '.yml', '.yaml', '.json'],
    },
]
