"""
Secrets & Credentials Detection Patterns
Hardcoded API keys, tokens, passwords, private keys across all file types.
"""

SECRETS_PATTERNS = [

    # ─────────────────────────────────────────────
    # CLOUD PROVIDER KEYS
    # ─────────────────────────────────────────────
    {
        'id': 'SEC-001',
        'category': 'Secrets: Cloud Credentials',
        'name': 'AWS Access Key ID',
        'severity': 'CRITICAL',
        'pattern': r'AKIA[0-9A-Z]{16}',
        'description': 'AWS Access Key ID detected in source code.',
        'fix': 'Remove immediately. Use IAM roles, env vars, or AWS Secrets Manager. Rotate the key NOW.',
        'langs': 'all',
        'cwe': 'CWE-798',
    },
    {
        'id': 'SEC-002',
        'category': 'Secrets: Cloud Credentials',
        'name': 'AWS Secret Access Key',
        'severity': 'CRITICAL',
        'pattern': r'(aws_secret_access_key|AWS_SECRET_ACCESS_KEY)\s*[=:]\s*["\']?[A-Za-z0-9/+]{40}["\']?',
        'description': 'AWS Secret Access Key hardcoded.',
        'fix': 'Use AWS IAM roles or aws-vault. Never hardcode AWS credentials.',
        'langs': 'all',
        'cwe': 'CWE-798',
    },
    {
        'id': 'SEC-003',
        'category': 'Secrets: Cloud Credentials',
        'name': 'Google API Key',
        'severity': 'CRITICAL',
        'pattern': r'AIza[0-9A-Za-z\-_]{35}',
        'description': 'Google API Key detected.',
        'fix': 'Restrict the key in Google Cloud Console. Move to environment variables.',
        'langs': 'all',
        'cwe': 'CWE-798',
    },
    {
        'id': 'SEC-004',
        'category': 'Secrets: Cloud Credentials',
        'name': 'Google OAuth Client Secret',
        'severity': 'CRITICAL',
        'pattern': r'(client_secret|GOOGLE_CLIENT_SECRET)\s*[=:]\s*["\'][A-Za-z0-9_\-]{24,}["\']',
        'description': 'Google OAuth client secret hardcoded.',
        'fix': 'Move to environment variables. Regenerate the secret.',
        'langs': 'all',
        'cwe': 'CWE-798',
    },
    {
        'id': 'SEC-005',
        'category': 'Secrets: Cloud Credentials',
        'name': 'Azure Connection String',
        'severity': 'CRITICAL',
        'pattern': r'DefaultEndpointsProtocol=https;AccountName=\w+;AccountKey=[A-Za-z0-9+/=]{88}',
        'description': 'Azure Storage connection string with account key.',
        'fix': 'Use Azure Managed Identity or Azure Key Vault.',
        'langs': 'all',
        'cwe': 'CWE-798',
    },
    {
        'id': 'SEC-006',
        'category': 'Secrets: Cloud Credentials',
        'name': 'GCP Service Account Key',
        'severity': 'CRITICAL',
        'pattern': r'"type"\s*:\s*"service_account"',
        'description': 'GCP service account JSON key file detected.',
        'fix': 'Use Workload Identity Federation or environment-based credentials. Never commit service account JSON.',
        'langs': 'all',
        'cwe': 'CWE-798',
    },

    # ─────────────────────────────────────────────
    # VERSION CONTROL & CI/CD TOKENS
    # ─────────────────────────────────────────────
    {
        'id': 'SEC-010',
        'category': 'Secrets: VCS Tokens',
        'name': 'GitHub Personal Access Token',
        'severity': 'CRITICAL',
        'pattern': r'ghp_[A-Za-z0-9]{36}',
        'description': 'GitHub Personal Access Token (classic) detected.',
        'fix': 'Revoke immediately at github.com/settings/tokens. Use GitHub Actions secrets.',
        'langs': 'all',
        'cwe': 'CWE-798',
    },
    {
        'id': 'SEC-011',
        'category': 'Secrets: VCS Tokens',
        'name': 'GitHub OAuth Token',
        'severity': 'CRITICAL',
        'pattern': r'gho_[A-Za-z0-9]{36}',
        'description': 'GitHub OAuth token detected.',
        'fix': 'Revoke immediately. Use GitHub Apps with fine-grained permissions.',
        'langs': 'all',
        'cwe': 'CWE-798',
    },
    {
        'id': 'SEC-012',
        'category': 'Secrets: VCS Tokens',
        'name': 'GitHub Actions Token',
        'severity': 'CRITICAL',
        'pattern': r'ghs_[A-Za-z0-9]{36}',
        'description': 'GitHub Actions server-to-server token detected.',
        'fix': 'These are temporary but should never appear in source code.',
        'langs': 'all',
        'cwe': 'CWE-798',
    },
    {
        'id': 'SEC-013',
        'category': 'Secrets: VCS Tokens',
        'name': 'GitLab Personal Access Token',
        'severity': 'CRITICAL',
        'pattern': r'glpat-[A-Za-z0-9_\-]{20}',
        'description': 'GitLab Personal Access Token detected.',
        'fix': 'Revoke at GitLab profile settings. Use CI/CD variables.',
        'langs': 'all',
        'cwe': 'CWE-798',
    },

    # ─────────────────────────────────────────────
    # PAYMENT & FINANCIAL
    # ─────────────────────────────────────────────
    {
        'id': 'SEC-020',
        'category': 'Secrets: Payment Keys',
        'name': 'Stripe Secret Key',
        'severity': 'CRITICAL',
        'pattern': r'sk_(live|test)_[A-Za-z0-9]{24,}',
        'description': 'Stripe secret key detected. Full API access to your Stripe account.',
        'fix': 'Revoke immediately at dashboard.stripe.com/apikeys. Use environment variables.',
        'langs': 'all',
        'cwe': 'CWE-798',
    },
    {
        'id': 'SEC-021',
        'category': 'Secrets: Payment Keys',
        'name': 'Stripe Publishable Key (Exposed in Backend)',
        'severity': 'MEDIUM',
        'pattern': r'pk_(live|test)_[A-Za-z0-9]{24,}',
        'description': 'Stripe publishable key in backend code (low risk but should be in env vars).',
        'fix': 'Move to environment variable. Publishable keys are client-safe but should not be hardcoded.',
        'langs': ['.py', '.js', '.ts', '.java', '.go', '.rb'],
        'cwe': 'CWE-798',
    },
    {
        'id': 'SEC-022',
        'category': 'Secrets: Payment Keys',
        'name': 'PayPal Credentials',
        'severity': 'CRITICAL',
        'pattern': r'(paypal_client_secret|PAYPAL_SECRET)\s*[=:]\s*["\'][A-Za-z0-9_\-]{20,}["\']',
        'description': 'PayPal client secret hardcoded.',
        'fix': 'Use PayPal SDK with environment-based credentials.',
        'langs': 'all',
        'cwe': 'CWE-798',
    },

    # ─────────────────────────────────────────────
    # COMMUNICATION / MESSAGING
    # ─────────────────────────────────────────────
    {
        'id': 'SEC-030',
        'category': 'Secrets: Messaging',
        'name': 'Slack Bot/Webhook Token',
        'severity': 'HIGH',
        'pattern': r'(xoxb|xoxe|xoxo|xoxp|xoxa)-[A-Za-z0-9\-]{10,}',
        'description': 'Slack token detected. Can read/write messages in your workspace.',
        'fix': 'Revoke at api.slack.com/apps. Store in environment variables.',
        'langs': 'all',
        'cwe': 'CWE-798',
    },
    {
        'id': 'SEC-031',
        'category': 'Secrets: Messaging',
        'name': 'Slack Webhook URL',
        'severity': 'HIGH',
        'pattern': r'hooks\.slack\.com/services/T[A-Za-z0-9]+/B[A-Za-z0-9]+/[A-Za-z0-9]+',
        'description': 'Slack incoming webhook URL exposed. Anyone can post to your channel.',
        'fix': 'Regenerate webhook. Store URL in environment variable.',
        'langs': 'all',
        'cwe': 'CWE-798',
    },
    {
        'id': 'SEC-032',
        'category': 'Secrets: Messaging',
        'name': 'Twilio Auth Token',
        'severity': 'CRITICAL',
        'pattern': r'(TWILIO_AUTH_TOKEN|twilio_auth_token)\s*[=:]\s*["\'][a-f0-9]{32}["\']',
        'description': 'Twilio authentication token hardcoded.',
        'fix': 'Revoke at twilio.com/console. Use environment variables.',
        'langs': 'all',
        'cwe': 'CWE-798',
    },
    {
        'id': 'SEC-033',
        'category': 'Secrets: Messaging',
        'name': 'Discord Bot Token',
        'severity': 'HIGH',
        'pattern': r'[MN][A-Za-z0-9]{23}\.[A-Za-z0-9_\-]{6}\.[A-Za-z0-9_\-]{27}',
        'description': 'Discord bot token detected. Full control over your Discord bot.',
        'fix': 'Reset token at discord.com/developers. Use environment variables.',
        'langs': 'all',
        'cwe': 'CWE-798',
    },
    {
        'id': 'SEC-034',
        'category': 'Secrets: Messaging',
        'name': 'SendGrid / Mailgun API Key',
        'severity': 'HIGH',
        'pattern': r'(SG\.[A-Za-z0-9_\-]{22}\.[A-Za-z0-9_\-]{43}|key-[a-z0-9]{32})',
        'description': 'SendGrid or Mailgun API key detected. Can send spam on your behalf.',
        'fix': 'Revoke key immediately. Use environment variables.',
        'langs': 'all',
        'cwe': 'CWE-798',
    },

    # ─────────────────────────────────────────────
    # AI / ML API KEYS
    # ─────────────────────────────────────────────
    {
        'id': 'SEC-040',
        'category': 'Secrets: AI/ML Keys',
        'name': 'OpenAI API Key',
        'severity': 'CRITICAL',
        'pattern': r'sk-[A-Za-z0-9]{48}',
        'description': 'OpenAI API key detected. Can be used to rack up charges on your account.',
        'fix': 'Revoke at platform.openai.com/api-keys. Use environment variables.',
        'langs': 'all',
        'cwe': 'CWE-798',
    },
    {
        'id': 'SEC-041',
        'category': 'Secrets: AI/ML Keys',
        'name': 'Anthropic API Key',
        'severity': 'CRITICAL',
        'pattern': r'sk-ant-[A-Za-z0-9\-_]{93}',
        'description': 'Anthropic Claude API key detected.',
        'fix': 'Revoke at console.anthropic.com. Use environment variables.',
        'langs': 'all',
        'cwe': 'CWE-798',
    },
    {
        'id': 'SEC-042',
        'category': 'Secrets: AI/ML Keys',
        'name': 'Hugging Face Token',
        'severity': 'HIGH',
        'pattern': r'hf_[A-Za-z0-9]{34,}',
        'description': 'Hugging Face access token detected.',
        'fix': 'Revoke at huggingface.co/settings/tokens. Use environment variables.',
        'langs': 'all',
        'cwe': 'CWE-798',
    },
    {
        'id': 'SEC-043',
        'category': 'Secrets: AI/ML Keys',
        'name': 'Replicate API Token',
        'severity': 'HIGH',
        'pattern': r'r8_[A-Za-z0-9]{40}',
        'description': 'Replicate API token detected.',
        'fix': 'Revoke at replicate.com/account. Use environment variables.',
        'langs': 'all',
        'cwe': 'CWE-798',
    },

    # ─────────────────────────────────────────────
    # DATABASE & INFRASTRUCTURE
    # ─────────────────────────────────────────────
    {
        'id': 'SEC-050',
        'category': 'Secrets: Database',
        'name': 'Database Connection String with Password',
        'severity': 'CRITICAL',
        'pattern': r'(postgresql|mysql|mongodb|redis|mssql|oracle):\/\/[^:]+:[^@\s]{3,}@',
        'description': 'Database connection string with embedded password.',
        'fix': 'Use environment variables for connection strings. Never hardcode DB credentials.',
        'langs': 'all',
        'cwe': 'CWE-798',
    },
    {
        'id': 'SEC-051',
        'category': 'Secrets: Database',
        'name': 'MongoDB URI with Credentials',
        'severity': 'CRITICAL',
        'pattern': r'mongodb(\+srv)?:\/\/[^:]+:[^@\s]+@[^/\s]+',
        'description': 'MongoDB connection URI with embedded credentials.',
        'fix': 'Use MONGODB_URI environment variable. Consider MongoDB Atlas connection strings with env vars.',
        'langs': 'all',
        'cwe': 'CWE-798',
    },
    {
        'id': 'SEC-052',
        'category': 'Secrets: Database',
        'name': 'Redis Auth URL',
        'severity': 'HIGH',
        'pattern': r'redis://:?[^@\s]+@[^/\s]+',
        'description': 'Redis connection URL with password.',
        'fix': 'Use REDIS_URL environment variable.',
        'langs': 'all',
        'cwe': 'CWE-798',
    },
    {
        'id': 'SEC-053',
        'category': 'Secrets: Database',
        'name': 'Generic Password in Config',
        'severity': 'HIGH',
        'pattern': r'(password|passwd|pwd|db_pass|database_password|DB_PASSWORD)\s*[=:]\s*["\'][^"\']{4,}["\']',
        'description': 'Password value hardcoded in configuration.',
        'fix': 'Load from environment variable: os.getenv("DB_PASSWORD") or process.env.DB_PASSWORD',
        'langs': ['.py', '.js', '.ts', '.java', '.go', '.php', '.rb', '.env', '.yaml', '.yml', '.toml'],
        'cwe': 'CWE-798',
    },

    # ─────────────────────────────────────────────
    # CRYPTOGRAPHIC MATERIAL
    # ─────────────────────────────────────────────
    {
        'id': 'SEC-060',
        'category': 'Secrets: Private Keys',
        'name': 'RSA/DSA/EC Private Key',
        'severity': 'CRITICAL',
        'pattern': r'-----BEGIN (RSA|DSA|EC|OPENSSH|PGP) PRIVATE KEY-----',
        'description': 'Private key embedded in source code. Complete compromise of all encrypted communications.',
        'fix': 'Remove immediately. Use key management systems (AWS KMS, HashiCorp Vault). Add *.pem to .gitignore.',
        'langs': 'all',
        'cwe': 'CWE-321',
    },
    {
        'id': 'SEC-061',
        'category': 'Secrets: Private Keys',
        'name': 'PEM Certificate with Private Key',
        'severity': 'CRITICAL',
        'pattern': r'-----BEGIN CERTIFICATE-----',
        'description': 'Certificate file detected in source code.',
        'fix': 'Store certificates in secure certificate stores. Add *.pem, *.crt, *.key to .gitignore.',
        'langs': 'all',
        'cwe': 'CWE-321',
    },

    # ─────────────────────────────────────────────
    # GENERIC PATTERNS
    # ─────────────────────────────────────────────
    {
        'id': 'SEC-070',
        'category': 'Secrets: Generic',
        'name': 'Generic API Key Assignment',
        'severity': 'HIGH',
        'pattern': r'(api_key|apikey|API_KEY|APIKEY)\s*[=:]\s*["\'][A-Za-z0-9_\-]{16,}["\']',
        'description': 'Generic API key hardcoded in source.',
        'fix': 'Move to environment variable: os.getenv("API_KEY") or process.env.API_KEY',
        'langs': 'all',
        'cwe': 'CWE-798',
    },
    {
        'id': 'SEC-071',
        'category': 'Secrets: Generic',
        'name': 'Bearer Token Hardcoded',
        'severity': 'HIGH',
        'pattern': r'["\']Bearer\s+[A-Za-z0-9_\-\.]{20,}["\']',
        'description': 'Bearer token hardcoded in source code.',
        'fix': 'Tokens must be loaded at runtime from env vars or secrets manager.',
        'langs': 'all',
        'cwe': 'CWE-798',
    },
    {
        'id': 'SEC-072',
        'category': 'Secrets: Generic',
        'name': '.env File Committed',
        'severity': 'CRITICAL',
        'pattern': r'^\.env$',
        'description': '.env file exists in repository root. All environment secrets may be exposed.',
        'fix': 'Add .env to .gitignore immediately. Use .env.example with dummy values for documentation.',
        'langs': ['.env'],
        'cwe': 'CWE-798',
        'file_check': True,
    },
]
